version: '3.8'
services:
  postgres:
    container_name: taralli-db-service
    image: postgres:17
    environment:
      POSTGRES_URL: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: taralli
      POSTGRES_DB: taralli-db
      POSTGRES_HOST_AUTH_METHOD: trust #add password later
    ports:
      - "5432:5432"