[package]
name = "taralli-provider-offering-client-bin"
version = "0.1.0"
edition = "2021"

[dependencies]
taralli-primitives = { workspace = true }
taralli-client = { path = "../../crates/taralli-client"}
taralli-worker = { path = "../../crates/taralli-worker"}
alloy = { workspace = true }
async-compression = "0.4.18"
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
reqwest = { workspace = true }
futures-util = { workspace = true }
futures = { workspace = true }
lazy_static = { workspace = true }
async-trait = { workspace = true }
url = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
sha3 = { workspace = true }
bytemuck = "1.21.0"
hex = "0.4.3"
rand = "0.8.5"
config = "0.14.0"
bincode = "1.1.3"
brotli = { workspace = true }
tokio-util = { workspace = true }
tokio-stream = "0.1.17"
ethers = { version = "2.0", features = ["ws", "rustls", "eip712"] }
risc0-zkvm = { version = "1.1.2", default-features = false, features = ["client"] }
tempfile = "3.14.0"
wasmer = "4.4.0"
num-bigint = "0.4.6"
tungstenite = "0.26.1"
tokio-tungstenite = "0.26.1"
color-eyre = { workspace = true }
anyhow = "1.0.86"
dotenv = { workspace = true }
