[profile.default]
src = "src"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./"}]
solc = "0.8.23"
optimizer = true
optimizer_runs = 100

[invariant]
runs = 100
depth = 100
fail_on_revert = true
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true
shrink_run_limit = 5000