[package]
name = "taralli-systems"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
async-trait = "0.1.83"

[dev-dependencies]
tokio = { workspace = true }
